/**
 * Custom Next.js image loader — serves pre-generated responsive WebP variants
 * from public/ instead of using Vercel Image Optimization.
 *
 * Variant naming convention (generated by optimize-all-images.mjs):
 *   foo.webp     → full size  (desktop, maxWidth per directory)
 *   foo-md.webp  → 960px max  (tablet)
 *   foo-sm.webp  → 480px max  (mobile)
 *
 * Next.js calls this loader for every srcset entry. The `width` param is the
 * candidate width Next.js wants to display; we map it to the nearest variant.
 */
export default function imageLoader({ src, width }: { src: string; width: number }): string {
    // Remote images (YouTube thumbnails, etc.) — return unchanged
    if (src.startsWith("http://") || src.startsWith("https://")) return src;

    // Bundled imports (/_next/static/media/...) — no variant files exist for these
    if (src.startsWith("/_next/")) return src;

    // Non-WebP local images — return unchanged (JPEG OG fallbacks, PNG icons)
    if (!src.endsWith(".webp")) return src;

    const base = src.slice(0, -5); // strip ".webp"
    if (width <= 480) return `${base}-sm.webp`;
    if (width <= 768) return `${base}-md.webp`;
    return src;
}
